In [ ]:
%pip install sqlalchemy pyodbc

In [ ]:
from datetime import date

from sqlalchemy import ForeignKey, create_engine, select, text
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
    sessionmaker,
)

In [ ]:
class Base(DeclarativeBase):
    pass

class Student(Base):
    __tablename__ = "student"

    student_id: Mapped[int] = mapped_column(primary_key=True, autoincrement=False)
    last_name: Mapped[str] = mapped_column()
    first_name: Mapped[str] = mapped_column()
    birth_date: Mapped[date] = mapped_column()
    login: Mapped[str] = mapped_column()
    year_result: Mapped[int] = mapped_column()
    section_id: Mapped[int] = mapped_column(ForeignKey("section.section_id"))
    course_id: Mapped[str] = mapped_column()

    section: Mapped["Section"] = relationship()

class Section(Base):
    __tablename__ = "section"
    section_id: Mapped[int] = mapped_column(primary_key=True, autoincrement=False)
    section_name: Mapped[str] = mapped_column()

    students: Mapped[list["Student"]] = relationship()

In [ ]:
# mssql+pyodbc://username:password@localhost:1433/nom_de_la_db
url_connection = "mssql+pyodbc://sa:test1234=@localhost:1433/dbslide"
url_connection += "?driver=ODBC+Driver+17+for+SQL+Server"

# création du moteur de connection à SQL server
engine = create_engine(url=url_connection, echo=True)

# ouverture d'une session
session_factory = sessionmaker(bind=engine)

In [ ]:
with session_factory() as session:
    # insertion d'un étudiant
    s = Student() # création d'un instance de Student
    # # modification des données de l'etudiant

    s.student_id = 99
    s.last_name = "LY"
    s.first_name = "Khun"
    s.year_result = 5
    s.section_id = 1110
    s.course_id = ""
    s.birth_date = date(1982, 5, 6)

    # sauvegarde
    session.add(s)
    session.commit()

In [ ]:
with session_factory() as session:
    query = select(Student).where(Student.student_id in [99, 42])
    khun = session.execute(query).scalars().one_or_none()
    if khun:
        session.delete(khun)
        session.commit()

In [ ]:
with session_factory() as session:
    query = text("SELECT s.last_name, se.section_name FROM student s JOIN section se ON se.section_id = s.section_id")
    print(session.execute(query).all())

In [ ]:
with session_factory() as session:
    query = select(Student)
    data = session.execute(query).scalars().all()
    for s in data:
        print(s.last_name, s.section.section_name)

In [ ]:
with session_factory() as session:
    query = select(Section)
    data = session.scalars(query).all()
    for se in data:
        print(se.section_name, [s.last_name for s in se.students])

In [ ]:
from sqlalchemy.orm import joinedload

with session_factory() as session:
    query = select(Section).options(joinedload(Section.students))
    data = session.scalars(query).unique().all()
    for sec in data:
        print(sec.section_name)
        print('--------------')
        for std in sec.students:
            print(std.last_name, std.first_name)
        print('--------------')

In [ ]:
import pandas as pd

with session_factory() as session:
    query = select(Student, Section.section_name).join(Student.section)
    # or query = text("
    # SELECT st.*, se.section_name 
    # FROM student st JOIN section se 
    # ON se.section_id = st.section_id")
    df = pd.read_sql(query, session.connection())
    display(df.head())
    display(df.tail())

In [44]:
with session_factory() as session:
    batches = pd.read_sql(select(Student), session.connection(), chunksize=2)
    for df in batches:
        display(df)

2026-10-13 11:45:14,888 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-10-13 11:45:14,889 INFO sqlalchemy.engine.Engine SELECT student.student_id, student.last_name, student.first_name, student.birth_date, student.login, student.year_result, student.section_id, student.course_id
FROM student
2026-10-13 11:45:14,890 INFO sqlalchemy.engine.Engine [cached since 4639s ago] ()

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,1,Lucas,Georges,1944-05-17,glucas,10,1320,EG2210
1,2,Eastwood,Clint,1930-05-31,ceastwoo,4,1010,EG2210

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,3,Connery,Sean,1930-08-25,sconnery,12,1020,EG2110
1,4,De Niro,Robert,1943-08-17,rde niro,3,1110,EG2210

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,5,Bacon,Kevin,1958-07-08,kbacon,16,1120,0
1,6,Basinger,Kim,1953-12-08,kbasinge,19,1310,0

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,7,Depp,Johnny,1963-06-09,jdepp,11,1110,EG2210
1,8,Roberts,Julia,1967-10-28,jroberts,17,1120,0

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,9,Portman,Natalie,1981-06-09,nportman,4,1010,EG2210
1,10,Clooney,Georges,1961-05-06,gclooney,4,1020,EG2110

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,11,Garcia,Andy,1956-04-12,agarcia,19,1110,0
1,12,Willis,Bruce,1955-03-19,bwillis,6,1010,EG2210

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,13,Cruise,Tom,1962-07-03,tcruise,4,1020,EG2110
1,14,Witherspoon,Reese,1976-03-22,rwithers,7,1020,EG1020

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,15,Marceau,Sophie,1966-11-17,smarceau,6,1110,0
1,16,Michelle Gellar,Sarah,1977-04-14,smichell,7,1020,EG2110

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,17,Milano,Alyssa,1972-12-19,amilano,7,1110,0
1,18,Garner,Jennifer,1972-04-17,jgarner,18,1120,0

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,19,Fox,Michael J.,1969-06-20,mfox,3,1310,0
1,20,Hanks,Tom,1956-07-09,thanks,8,1020,EG2110

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,21,Morse,David,1953-10-11,dmorse,2,1110,0
1,22,Bullock,Sandra,1964-07-26,sbullock,2,1010,EG1020

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,23,Reeves,Keanu,1964-09-02,kreeves,10,1020,EG2210
1,24,Doherty,Shannen,1971-04-12,sdoherty,2,1320,EG2120

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,25,Berry,Halle,1966-08-14,hberry,18,1320,EG2210
1,66,Paul,Doe,None,NaN,12,1110,

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,67,Steve,Henri,None,None,17,1120,
1,68,Paul,Doe,None,None,12,1110,

,student_id,last_name,first_name,birth_date,login,year_result,section_id,course_id
0,69,Steve,Henri,None,None,17,1120,
1,99,LY,Khun,1982-05-06,None,5,1110,

2026-10-13 11:45:14,984 INFO sqlalchemy.engine.Engine ROLLBACK

In [ ]:
df = pd.DataFrame([
    { "student_id": "68", "last_name": "Paul", "first_name": "Doe", 
     "year_result": 12, "section_id": 1110, "course_id": "" },
    { "student_id": "69", "last_name": "Steve", "first_name": "Henri", 
        "year_result": 17, "section_id": 1120, "course_id": "" }
])
# from sqlalchemy import insert
# with session_factory() as session:
#     session.execute(insert(Student), df.to_dict(orient="records"))
#     session.commit()

with session_factory() as session:
    df.to_sql("student",con=session.connection(),if_exists="append", index=False)
    session.commit()

2026-10-13 11:44:53,279 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-10-13 11:44:53,281 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
FROM [INFORMATION_SCHEMA].[TABLES]
WHERE ([INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) OR [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max))) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2026-10-13 11:44:53,281 INFO sqlalchemy.engine.Engine [cached since 103s ago] ('BASE TABLE', 'VIEW', 'student', 'dbo')
2026-10-13 11:44:53,349 INFO sqlalchemy.engine.Engine INSERT INTO student (student_id, last_name, first_name, year_result, section_id, course_id) VALUES (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?)
2026-10-13 11:44:53,350 INFO sqlalchemy.engine.Engine [generated in 0.00012s (insertmanyvalues) 1/1 (unordered)] ('68', 'Paul', 'Doe', 12, 1110, '', '69', 'Steve', 'Henri', 17, 1120, '')
2026-10-13 11:44:53,358 INFO sqlalchemy.engine.Engine COMMIT